spring.application.name=SupportTicketV1
spring.datasource.url=jdbc:mysql://localhost:3306/support-ticker
spring.datasource.username=root
spring.datasource.password=3018
spring.jpa.hibernate.ddl-auto=update
jwt.secretkey=thisismyverylongsupersecretkeyyouidioticsupidfellowjustfollowtheinstruction