package com.abdul.SupportTicketV1.enums;

public enum Permission {
	GET_TICKET,
	PATCH_TICKET,
	POST_TICKET,
	PUT_TICKET,
	DELETE_TICKET,
	RESOLVE_TICKET,
	ASSIGN_TICKET,
	GET_USER,
	POST_USER,
	PUT_USER,
	PATCH_USER,
	DELETE_USER,
	CHANGE_ROLE_SUPPORT,
	CHANGE_ROLE_ADMIN
}
